-- Bank_management _project

create database BMS_DB1;
use   BMS_DB1;
show databases;

-- CUSTOMER_PERSONAL_INFO1
CREATE TABLE CUSTOMER_PERSONAL_INFO2(
    CUSTOMER_ID  VARCHAR(5),
	CUSTOMER_NAME VARCHAR(30),
    DATE_OF_BIRTH DATE,
    GUARDIAN_NAME VARCHAR(30),
    ADDRESS VARCHAR(50),
    CONTACT_NO BIGINT(10),
    MAIL_ID VARCHAR(30),
    GENDER CHAR(1),
    MARITAL_STATUS VARCHAR(10),
    IDENTIFICATION_DOC_TYPE VARCHAR(20),
    ID_DOC_NO VARCHAR(20),
    CITIZENSHIP VARCHAR(10),
    constraint CUST_PERS_INFO_PK PRIMARY KEY(CUSTOMER_ID)
    );
    show tables;
    
    -- CREATE TABLE OF CUSTOMER_REFERENCE_INFO
    CREATE TABLE CUSTOMER_REFERENCE_INFO
    (
     CUSTOMER_ID  VARCHAR(5),
	REFERENCE_ACC_NAME VARCHAR(20),
    REFERENCE_ACC_NO BIGINT(16),
    REFERENCE_ACC_ADDRESS VARCHAR(50),
    RELATION VARCHAR(25),
   CONSTRAINT  CUST_PERS_INFO_PK PRIMARY KEY(CUSTOMER_ID),
   CONSTRAINT CUST_PERS_INFO_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER_PERSONAL_INFO2 (CUSTOMER_ID)
    );
   show tables;
   
   -- CREATE TABLE OF  BANK_INFO
   
   CREATE TABLE  BANK_INFO
   (
   IFSC_CODE VARCHAR(15),
   BANK_NAME VARCHAR(25),
   BRANCH_NAME VARCHAR(25),
   CONSTRAINT BANK_INFO_PK PRIMARY KEY(IFSC_CODE)
   );
   SHOW TABLES;
   
   --  TABLE OF ACCOUNT_INFO
   
   CREATE TABLE ACCOUNT_INFO
   (
   ACCOUNT_NO BIGINT(16),
   CUSTOMER_ID VARCHAR(5),
   ACCOUNT_TYPE VARCHAR(10),
   REGISTRACTION_DATE DATE,
   ACTIVATION_DATE DATE,
   IFSC_CODE VARCHAR(10),
   INTEREST DECIMAL(7,2),
   INITIAL_DEPOSIT BIGINT(10),
   CONSTRAINT ACC_INFO_PK PRIMARY KEY(ACCOUNT_NO),
    CONSTRAINT ACC_INFO_PERS_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER_PERSONAL_INFO2(CUSTOMER_ID),
   CONSTRAINT ACC_INFO_BANK_FK  FOREIGN KEY (IFSC_CODE) REFERENCES BANK_INFO(IFSC_CODE)
);
SHOW TABLES;
SELECT* FROM  ACCOUNT_INFO;

-- BANK_INFO

INSERT INTO BANK_INFO(IFSC_CODE,BANK_NAME,BRANCH_NAME)VALUES('HDVL0012','HDFC', 'SANGLI');
INSERT INTO BANK_INFO(IFSC_CODE,BANK_NAME,BRANCH_NAME)VALUES('SBITNO123','SBI', 'ISLAMPUR');
INSERT INTO BANK_INFO(IFSC_CODE,BANK_NAME,BRANCH_NAME)VALUES('ICITN0232','ICICI', 'TNAGAR');
INSERT INTO BANK_INFO(IFSC_CODE,BANK_NAME,BRANCH_NAME)VALUES('INDIA0007','BANK OF INDIA', 'ISLAMPUR');
INSERT INTO BANK_INFO(IFSC_CODE,BANK_NAME,BRANCH_NAME)VALUES('HDVL0780','HDFC', 'SATARA');
SELECT* FROM BANK_INFO;

-- CUSTOMER_PERSONAL_INFO
INSERT INTO CUSTOMER_PERSONAL_INFO (CUSTOMER_ID, CUSTOMER_NAME, DATE_OF_BIRTH, GUARDIAN_NAME, ADDRESS, CONTACT_NO, MAIL_ID, GENDER, MARITAL_STATUS, IDENTIFICATION_DOC_TYPE, ID_DOC_NO)
VALUES ('CU1', 'John Doe', '1990-05-15', 'Jane Doe', '123 Main St', 1234567890, 'john@example.com', 'M', 'Single', 'Passport', 'ABC123456');
INSERT INTO CUSTOMER_PERSONAL_INFO (CUSTOMER_ID, CUSTOMER_NAME, DATE_OF_BIRTH, GUARDIAN_NAME, ADDRESS, CONTACT_NO, MAIL_ID, GENDER, MARITAL_STATUS, IDENTIFICATION_DOC_TYPE, ID_DOC_NO)
VALUES ('CU2', 'SANIKA PATIL', '2002-12-07', 'SANIKA PATIL', '123 Main St JUNEKHED', 7218807515, 'SANIKAP043@GMAIL.com', 'F', 'Single', 'Passport', 'ABC12377');
INSERT INTO CUSTOMER_PERSONAL_INFO (CUSTOMER_ID, CUSTOMER_NAME, DATE_OF_BIRTH, GUARDIAN_NAME, ADDRESS, CONTACT_NO, MAIL_ID, GENDER, MARITAL_STATUS, IDENTIFICATION_DOC_TYPE, ID_DOC_NO)
VALUES ('CU3', 'SOHAN PATIL', '2004-12-30', 'SOHAN  PATIL', '123 Main St JUNEKHED', 1567890367, 'SOHAN@example.com', 'M', 'Single', 'Passport', 'ABC1234789');
INSERT INTO CUSTOMER_PERSONAL_INFO(CUSTOMER_ID, CUSTOMER_NAME, DATE_OF_BIRTH, GUARDIAN_NAME, ADDRESS, CONTACT_NO, MAIL_ID, GENDER, MARITAL_STATUS, IDENTIFICATION_DOC_TYPE, ID_DOC_NO)
VALUES ('CU4', 'RAVINA PATIL', '1996-12-15', 'RAVINA  PATIL', '143 MAIN SEA BEACH ', 1567890411, 'RAVINA@example.com', 'F', 'Single', 'Passport', 'ILU12346709');
INSERT INTO CUSTOMER_PERSONAL_INFO (CUSTOMER_ID, CUSTOMER_NAME, DATE_OF_BIRTH, GUARDIAN_NAME, ADDRESS, CONTACT_NO, MAIL_ID, GENDER, MARITAL_STATUS, IDENTIFICATION_DOC_TYPE, ID_DOC_NO)
VALUES ('CU5', 'SANVI PATIL', '2027-12-22', ' SANVI PATIL', '143 MAIN SEA BEACH ', 9823350890, 'SANVI@example.com', 'F', 'Single', 'Passport', 'ILU1278965');

SELECT * FROM CUSTOMER_PERSONAL_INFO;


   
      
    
