-- Bank_management _project

create database BMS_DB1;
use   BMS_DB1;
show databases;

-- CUSTOMER_PERSONAL_INFO1
CREATE TABLE CUSTOMER_PERSONAL_INFO2(
    CUSTOMER_ID  VARCHAR(5),
	CUSTOMER_NAME VARCHAR(30),
    DATE_OF_BIRTH DATE,
    GUARDIAN_NAME VARCHAR(30),
    ADDRESS VARCHAR(50),
    CONTACT_NO BIGINT(10),
    MAIL_ID VARCHAR(30),
    GENDER CHAR(1),
    MARITAL_STATUS VARCHAR(10),
    IDENTIFICATION_DOC_TYPE VARCHAR(20),
    ID_DOC_NO VARCHAR(20),
    CITIZENSHIP VARCHAR(10),
    constraint CUST_PERS_INFO_PK PRIMARY KEY(CUSTOMER_ID)
    );
    show tables;
    
    -- CREATE TABLE OF CUSTOMER_REFERENCE_INFO
    CREATE TABLE CUSTOMER_REFERENCE_INFO
    (
     CUSTOMER_ID  VARCHAR(5),
	REFERENCE_ACC_NAME VARCHAR(20),
    REFERENCE_ACC_NO BIGINT(16),
    REFERENCE_ACC_ADDRESS VARCHAR(50),
    RELATION VARCHAR(25),
   CONSTRAINT  CUST_PERS_INFO_PK PRIMARY KEY(CUSTOMER_ID),
   CONSTRAINT CUST_PERS_INFO_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER_PERSONAL_INFO2 (CUSTOMER_ID)
    );
   show tables;
   
   -- CREATE TABLE OF  BANK_INFO
   
   CREATE TABLE  BANK_INFO
   (
   IFSC_CODE VARCHAR(15),
   BANK_NAME VARCHAR(25),
   BRANCH_NAME VARCHAR(25),
   CONSTRAINT BANK_INFO_PK PRIMARY KEY(IFSC_CODE)
   );
   SHOW TABLES;
   
   --  TABLE OF ACCOUNT_INFO
   
   CREATE TABLE ACCOUNT_INFO
   (
   
   
   
      
    
